2020-03-25 22:28:21,918 - instabot version: 0.115.0 (bot) - INFO - Instabot version: 0.115.0 Started
2020-03-25 22:28:21,919 - instabot version: 0.115.0 (bot) - DEBUG - Bot imported from /usr/local/lib/python2.7/dist-packages/instabot/bot/bot.pyc
2020-03-25 22:28:21,924 - instabot version: 0.115.0 (api_login) - DEBUG - Loading cookies
2020-03-25 22:28:21,925 - instabot version: 0.115.0 (api_login) - DEBUG - Loading uuids
2020-03-25 22:28:21,925 - instabot version: 0.115.0 (api_login) - INFO - Recovery from /var/www/html/example.com/public_html/cron/insta/config/menabungtanah_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=a30092fa-e99d-46c6-b2c6-a80dfd9fe9e9
- uuid=8aacbd94-8261-42c3-ae0d-d5476e870db9
- client_session_id=58f5fd4f-f694-43c5-a410-2c4a9174485e
- device_id=android-d13a49bfddbe7ce7
2020-03-25 22:28:21,925 - instabot version: 0.115.0 (api_login) - INFO - LOGIN FLOW! Just logged-in: False
2020-03-25 22:28:22,594 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: feed/timeline/ returned response: <Response [400]>
2020-03-25 22:28:22,595 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/feed/timeline/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:28:22,595 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:28:22,596 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:28:22,596 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:28:23,165 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: feed/reels_tray/ returned response: <Response [400]>
2020-03-25 22:28:23,165 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/feed/reels_tray/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:28:23,165 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:28:23,167 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:28:23,167 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:28:23,168 - instabot version: 0.115.0 (api) - INFO - Login flow failed, the cookie is broken. Relogin again.
2020-03-25 22:28:23,168 - instabot version: 0.115.0 (api_login) - DEBUG - Loading cookies
2020-03-25 22:28:23,169 - instabot version: 0.115.0 (api_login) - DEBUG - Loading uuids
2020-03-25 22:28:23,169 - instabot version: 0.115.0 (api_login) - INFO - Recovery from /var/www/html/example.com/public_html/cron/insta/config/menabungtanah_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=a30092fa-e99d-46c6-b2c6-a80dfd9fe9e9
- uuid=8aacbd94-8261-42c3-ae0d-d5476e870db9
- client_session_id=58f5fd4f-f694-43c5-a410-2c4a9174485e
- device_id=android-d13a49bfddbe7ce7
2020-03-25 22:28:23,170 - instabot version: 0.115.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-03-25 22:28:24,785 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [400]>
2020-03-25 22:28:24,787 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/get_prefill_candidates/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:28:24,789 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:28:24,789 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:28:24,790 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:28:25,791 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [400]>
2020-03-25 22:28:25,792 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/qe/sync/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:28:25,792 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:28:25,793 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:28:25,794 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:28:26,947 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [429]>
2020-03-25 22:28:26,948 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "prefetch disabled", "status": "fail"}
2020-03-25 22:28:26,948 - instabot version: 0.115.0 (api) - ERROR - Request returns 429 error!
2020-03-25 22:28:26,949 - instabot version: 0.115.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
2020-03-25 22:28:50,274 - instabot version: 0.115.0 (bot) - INFO - Instabot version: 0.115.0 Started
2020-03-25 22:28:50,274 - instabot version: 0.115.0 (bot) - DEBUG - Bot imported from /usr/local/lib/python2.7/dist-packages/instabot/bot/bot.pyc
2020-03-25 22:28:50,277 - instabot version: 0.115.0 (api_login) - DEBUG - Loading cookies
2020-03-25 22:28:50,278 - instabot version: 0.115.0 (api_login) - DEBUG - Loading uuids
2020-03-25 22:28:50,278 - instabot version: 0.115.0 (api_login) - INFO - Recovery from /var/www/html/example.com/public_html/cron/insta/config/menabungtanah_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=a30092fa-e99d-46c6-b2c6-a80dfd9fe9e9
- uuid=8aacbd94-8261-42c3-ae0d-d5476e870db9
- client_session_id=58f5fd4f-f694-43c5-a410-2c4a9174485e
- device_id=android-d13a49bfddbe7ce7
2020-03-25 22:28:50,278 - instabot version: 0.115.0 (api_login) - INFO - LOGIN FLOW! Just logged-in: False
2020-03-25 22:28:51,513 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: feed/timeline/ returned response: <Response [400]>
2020-03-25 22:28:51,514 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/feed/timeline/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:28:51,514 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:28:51,517 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:28:51,517 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:28:52,941 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: feed/reels_tray/ returned response: <Response [400]>
2020-03-25 22:28:52,942 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/feed/reels_tray/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:28:52,942 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:28:52,944 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:28:52,945 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:28:52,948 - instabot version: 0.115.0 (api) - INFO - Login flow failed, the cookie is broken. Relogin again.
2020-03-25 22:28:52,950 - instabot version: 0.115.0 (api_login) - DEBUG - Loading cookies
2020-03-25 22:28:52,954 - instabot version: 0.115.0 (api_login) - DEBUG - Loading uuids
2020-03-25 22:28:52,954 - instabot version: 0.115.0 (api_login) - INFO - Recovery from /var/www/html/example.com/public_html/cron/insta/config/menabungtanah_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=a30092fa-e99d-46c6-b2c6-a80dfd9fe9e9
- uuid=8aacbd94-8261-42c3-ae0d-d5476e870db9
- client_session_id=58f5fd4f-f694-43c5-a410-2c4a9174485e
- device_id=android-d13a49bfddbe7ce7
2020-03-25 22:28:52,956 - instabot version: 0.115.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-03-25 22:28:54,187 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [400]>
2020-03-25 22:28:54,188 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/get_prefill_candidates/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:28:54,189 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:28:54,190 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:28:54,190 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:28:54,811 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [400]>
2020-03-25 22:28:54,811 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/qe/sync/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:28:54,811 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:28:54,812 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:28:54,812 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:28:56,344 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [400]>
2020-03-25 22:28:56,345 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/launcher/sync/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:28:56,345 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:28:56,346 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:28:56,347 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:28:56,923 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [400]>
2020-03-25 22:28:56,924 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/contact_point_prefill/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:28:56,924 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:28:56,926 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:28:56,926 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:29:08,820 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-03-25 22:29:08,820 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/login/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:29:08,820 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:29:08,821 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:29:08,822 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:29:08,822 - instabot version: 0.115.0 (api) - ERROR - Failed to login go to instagram and change your password
2020-03-25 22:29:08,823 - instabot version: 0.115.0 (api) - INFO - Username or password is incorrect.
